config/routes.rb
SampleApp::Application.routes.draw do

  resources :objectbases

  resources :newsletters

  # http://guides.rubyonrails.org/i18n.html
  scope "/:locale" do
  end

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  root 'static_pages#home'
  #match '/privacy_and_security', to: 'static_pages#privacy_and_security', via: 'get'
  #match '/terms_of_use', to: 'static_pages#terms_of_use', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #match '/help',    to: 'static_pages#help',    via: 'get'
  #match '/about',   to: 'static_pages#about',   via: 'get'
  #match '/contact', to: 'static_pages#contact', via: 'get'


  get 'sitemap.xml', to: 'sitemap#index', as: 'sitemap', defaults: { format: 'xml' }

end

app/views/layouts/_admin.html.erb
</br>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= (t 'admin.admin_management') %></h3>
        </div>
        <div class="panel-body">
          <%= link_to (t 'admin.users'), users_path, class: "btn btn-sm btn-primary" %> |
          <%= link_to (t 'admin.mails'), newsletters_path, class: "btn btn-sm btn-warning" %> |
          <%= link_to (t 'admin.site_mobile_version_check'), {:mobile => 1}, class: "btn btn-sm btn-info" %> | | | |

          <%= link_to (t 'newsletters.new'), new_newsletter_path, class: "btn btn-sm btn-warning" %> | | | |
          <%= link_to (t 'Sign out'), signout_path, method: "delete", class: "btn btn-sm btn-danger" %> |
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.teleport-ds.com/">www.fpoi.net</a>
    All Rights Reserved, 2014. Created by <a href="http://proalab.com/" target="_blank">Proalab</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="menu" id="menu">
<div class="wrapper">
  <div class="text-center">
  <%= link_to image_tag("logo200.png", alt: "StartUp world map"), root_path, :class => "brand" %>
  </div>
<div class="head">
  <div>
    <h6>
      This map was made to connect and promote world startup community. Put yourself on the map!
    </h6>
  </div>
</div>
  <div class="head" style="text-align: center">
  <%= link_to new_objectbasis_path do %>
  <button type="button" class="btn btn-default btn-success btn-xs">
    <span class="glyphicon glyphicon-plus"></span> Add your StartUp now!
  </button>
  <% end %>
  </div>
  <div class="head">
  <div class="form-group">
    <input type="email" class="form-control input-sm" id="exampleInputEmail1" placeholder="Enter company name...">
  </div>
  </div>

  <% @startup = Objectbase.where(company_type: "StartUp").count %>
  <% @accelerator = Objectbase.where(company_type: "Accelerator").count %>
  <% @incubator = Objectbase.where(company_type: "Incubator").count %>
  <% @coworking = Objectbase.where(company_type: "Coworking").count %>
  <% @investor = Objectbase.where(company_type: "Investor").count %>
  <% @consalting = Objectbase.where(company_type: "Consalting").count %>
  <% @event = Objectbase.where(company_type: "Event").count %>

  <ul class="list-group">
    <li class="list-group-item">
      <span class="badge"><%= @startup %></span>
      <%= image_tag("startup.png") %> StartUp
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @accelerator %></span>
      <%= image_tag("accelerator.png") %> Accelerator
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @incubator %></span>
      <%= image_tag("incubator.png") %> Incubator
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @coworking %></span>
      <%= image_tag("coworking.png") %> Coworking
    </li>
    <!--<li class="list-group-item">
      <span class="badge"><%= @investor %></span>
      <%= image_tag("investor.png") %> Investor
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @consalting %></span>
      <%= image_tag("service.png") %> Consalting
    </li>
    <li class="list-group-item">
      <span class="badge"><%= @event %></span>
      <%= image_tag("event.png") %> Event
    </li>-->
  </ul>

</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag '16_16_0.png' %>
    <!-- Google maps -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <%= javascript_include_tag "google_maps" %>
    <!-- Google maps -->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=en"></script>
    <%= javascript_include_tag "google_maps_autocomplete" %>
    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-51969081-1', 'fpoi.net');
        ga('send', 'pageview');

    </script>
    <!-- Google Analytics -->
  </head>
  <body onload="initialize(), setMarkers()">
    <%= render 'layouts/header' %>
    <%= content = yield %>
    <!--Back To Top Button-->
  <% if current_user.try(:admin?) %>
      <%= render 'layouts/admin' %>
  <% else %>
  <% end %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>